import { MovieListPage } from '@/components/MovieListPage/MovieListPage'
import './globals.css'
import { Inter } from 'next/font/google'
import { SortOption } from '@/models/enum/SortOption'
import { Genre } from "@/models/enum/MenuGenre";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


type NewType = SortOption

interface SearchQueryParameters {
  query?: string | null,
  sorting?: NewType | null,
  genre?: Genre | null,
}

export default function RootLayout({ children, query}: { children: React.ReactNode, query : SearchQueryParameters }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MovieListPage searchParams={query} >{children}</MovieListPage>
      </body>
    </html>
  )
}
